// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Simple movies API
//
//  This is a simple API
//  Schemes:
//    https
//  Host: virtserver.swaggerhub.com
//  BasePath: /damianr1602/chmury/1.0.0
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <damianr1602@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
