// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddDeviceHandlerFunc turns a function with the right signature into a add device handler
type AddDeviceHandlerFunc func(AddDeviceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddDeviceHandlerFunc) Handle(params AddDeviceParams) middleware.Responder {
	return fn(params)
}

// AddDeviceHandler interface for that can handle valid add device params
type AddDeviceHandler interface {
	Handle(AddDeviceParams) middleware.Responder
}

// NewAddDevice creates a new http.Handler for the add device operation
func NewAddDevice(ctx *middleware.Context, handler AddDeviceHandler) *AddDevice {
	return &AddDevice{Context: ctx, Handler: handler}
}

/*AddDevice swagger:route POST /movies admins addDevice

adds a device

Adds an item to the system

*/
type AddDevice struct {
	Context *middleware.Context
	Handler AddDeviceHandler
}

func (o *AddDevice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddDeviceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
