// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/damianr1602/chmuryrest/swagger/models"
)

// NewAddInventoryParams creates a new AddInventoryParams object
// no default values defined in spec.
func NewAddInventoryParams() AddInventoryParams {

	return AddInventoryParams{}
}

// AddInventoryParams contains all the bound params for the add inventory operation
// typically these are obtained from a http.Request
//
// swagger:parameters addInventory
type AddInventoryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Inventory item to add
	  In: body
	*/
	Device *models.Movie
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddInventoryParams() beforehand.
func (o *AddInventoryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Movie
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("device", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Device = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
