// Code generated by go-swagger; DO NOT EDIT.

package api_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/damianr1602/chmuryrest/swagger/models"
)

// DeleteMovieOKCode is the HTTP code returned for type DeleteMovieOK
const DeleteMovieOKCode int = 200

/*DeleteMovieOK movie deleted successfully

swagger:response deleteMovieOK
*/
type DeleteMovieOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteMovieOK creates DeleteMovieOK with default headers values
func NewDeleteMovieOK() *DeleteMovieOK {

	return &DeleteMovieOK{}
}

// WithPayload adds the payload to the delete movie o k response
func (o *DeleteMovieOK) WithPayload(payload *models.Result) *DeleteMovieOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete movie o k response
func (o *DeleteMovieOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMovieOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteMovieUnauthorizedCode is the HTTP code returned for type DeleteMovieUnauthorized
const DeleteMovieUnauthorizedCode int = 401

/*DeleteMovieUnauthorized Unauthorized

swagger:response deleteMovieUnauthorized
*/
type DeleteMovieUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteMovieUnauthorized creates DeleteMovieUnauthorized with default headers values
func NewDeleteMovieUnauthorized() *DeleteMovieUnauthorized {

	return &DeleteMovieUnauthorized{}
}

// WithPayload adds the payload to the delete movie unauthorized response
func (o *DeleteMovieUnauthorized) WithPayload(payload *models.Result) *DeleteMovieUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete movie unauthorized response
func (o *DeleteMovieUnauthorized) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMovieUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteMovieNotFoundCode is the HTTP code returned for type DeleteMovieNotFound
const DeleteMovieNotFoundCode int = 404

/*DeleteMovieNotFound The specified resource was not found

swagger:response deleteMovieNotFound
*/
type DeleteMovieNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteMovieNotFound creates DeleteMovieNotFound with default headers values
func NewDeleteMovieNotFound() *DeleteMovieNotFound {

	return &DeleteMovieNotFound{}
}

// WithPayload adds the payload to the delete movie not found response
func (o *DeleteMovieNotFound) WithPayload(payload *models.Result) *DeleteMovieNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete movie not found response
func (o *DeleteMovieNotFound) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMovieNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
