// Code generated by go-swagger; DO NOT EDIT.

package developers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewConfigureParams creates a new ConfigureParams object
// no default values defined in spec.
func NewConfigureParams() ConfigureParams {

	return ConfigureParams{}
}

// ConfigureParams contains all the bound params for the configure operation
// typically these are obtained from a http.Request
//
// swagger:parameters configure
type ConfigureParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*pass an optional search string for looking up inventory
	  In: query
	*/
	SearchString *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewConfigureParams() beforehand.
func (o *ConfigureParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qSearchString, qhkSearchString, _ := qs.GetOK("searchString")
	if err := o.bindSearchString(qSearchString, qhkSearchString, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSearchString binds and validates parameter SearchString from query.
func (o *ConfigureParams) bindSearchString(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.SearchString = &raw

	return nil
}
